[package]
name = "openvm-tests"
version = "0.1.0"
edition = "2021"

[dependencies]

openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", features = [
    "std",
] }
openvm-algebra-complex-macros = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", default-features = false }
openvm-algebra-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", default-features = false }
openvm-bigint-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", default-features = false }
openvm-ecc-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", default-features = false, features = ["k256"] }
openvm-pairing-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", default-features = false, features = [
    "bn254",
    "halo2curves",
] }
openvm-rv32im-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", default-features = false }
openvm-keccak256-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "830053d", default-features = false }

primeorder = { version = "0.13" }
hex = "0.4.3"
